Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/12/2022
Var
// Seção de Declarações das variáveis 
   nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite seu nome: ")
leia(nome)
escreva("Muito prazer, ", nome, "!")


Fimalgoritmo